### ISSUE TITLE
Automatised upgrades

### ISSUE THREAD

**Issue by jaroslawhartman** [jaroslawhartman/TimeZones-Alfred#46]
Implement an option for automatic (or at least _automatised_) upgrades.

Note to self - one liner to download last release:
* https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8
* ``` curl -s https://api.github.com/repos/jaroslawhartman/TimeZones-Alfred/releases/latest | grep "browser_download_url.*alfredworkflow" | cut -d : -f 2,3 | tr -d \" | wget -qi -```

**Comment by inspiredearth** [comment]
Yes, indeed ... automated updates would be nice. 
Thanks for the one-liner.

**Comment by xilopaint** [comment]
Regarding automatic updates I can see [OneUpdater](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) is mentioned in the credits but I can't see any sign of it being implemented.

**Comment by jaroslawhartman** [comment]
Fixed in 2.50

**Comment by xilopaint** [comment]
> Fixed in 2.50

I think connecting an OneUpdater node to the script filter is a much better implementation since people will get the update just by invoking the `tz` keyword.I think connecting an OneUpdater node to the script filter is a much better implementation since people will get the update just by invoking the [background=#eee][font=courier,monospace]tz[/font][/background] keyword.

**Comment by xilopaint** [comment]
> Fixed in 2.50

I think connecting an OneUpdater node to the script filter is a much better implementation since people will get the update just by invoking the `tz` keyword.

**Comment by jaroslawhartman** [comment]
> since people will get the update just by invoking the tz keyword.

It is exactly how it works.

Best regards

**Comment by xilopaint** [comment]
Oh, now I get what you did.
