### ISSUE TITLE
Sorting options for saved cities

### ISSUE THREAD

**Issue by villeodell** [jaroslawhartman/TimeZones-Alfred#9]
Hi there, love the workflow and appreciate the updates. 

Have you ever considered adding options for sorting the saved cities? It would be really great to have options like:

- sort cities East to West or West to East
- save a 'favourite/home' city that always appears at the top

Of course, one can accomplish it manually -- but it might be a nice enhancement to have this built in.

**Comment by jaroslawhartman** [comment]
Hi @villeodell 

Thank you for these suggestions. Right now it's just sorting alphabetically.

- Idea of sorting East to West or West to East is appealing but I'm not sure if this could be (easily) implemented. I will take a look.
- Adding a Favourite flag to the city/-ies sounds like a really good idea and should be possible to implement.

Adding to the backlog, I will keep you updated via this ticket.

Thank you,
Jarek

**Comment by jaroslawhartman** [comment]
> I don't have a lot of experience with shell script but one way to achieve sorting might be to just use/store the UTC offset in timezones.txt and then use sort

Very much indeed... Will take a look over the weekend.

Thank you,
Jarek

**Comment by jaroslawhartman** [comment]
Enhancement #9 - favourite cities. Download release v2.3.

![mymovie](https://user-images.githubusercontent.com/964833/48945403-7c6d4180-ef2a-11e8-9b09-c73ac28e1806.gif)

**Comment by jjarava** [comment]
Hi, @jaroslawhartman 

Just upgraded to v2.4 from the latest version, and while the ability to "star" cities is great, in the previous version if you hand-sorted the .txt file where the cities are stored, then that order would be kept.

For now, since you're sorting alphabetically I can sort-of regain that by changing the data file and adding a number to the name....

![image](https://user-images.githubusercontent.com/2682444/57142808-c1d94900-6dbd-11e9-9031-71d47a04705a.png)

But that messes up the city search, as it's searching from the beginning of the name (could you do partial searching by the names? That'd be cool!)

So being able to sort either by *not* doing alphabetically but just keeping the order on the data file, **or** implementing east-to-west or west-to-east ordering (i.e., sorting based on the TZ as suggested above) would be great!

**Comment by himat** [comment]
@jjarava I had the same issue with the sorting not being good. So I removed the sorting entirely so that it just uses the order specified by the cities in your cities file. You can get it https://github.com/himat/TimeZones-Alfred.

**Comment by jaroslawhartman** [comment]
Fixed in version v2.12:

Added an option to enable or disable sorting:

<img width="605" alt="Enable disable" src="https://user-images.githubusercontent.com/964833/63022235-c2947780-bea2-11e9-82ac-f3e956eaaa03.png">

When disabled, the order from `timezones.txt` is preserved:

<img width="605" alt="Disabled" src="https://user-images.githubusercontent.com/964833/63022288-da6bfb80-bea2-11e9-909c-9d34031e9989.png">

![Disabled-list](https://user-images.githubusercontent.com/964833/63022294-df30af80-bea2-11e9-862b-e54040fb7079.png)

Configuration file `timezones.txt` can be updated by selecting Edit option:

<img width="605" alt="Screenshot 2019-08-14 at 14 51 07" src="https://user-images.githubusercontent.com/964833/63022339-fa032400-bea2-11e9-87fa-a1be7aabc07b.png">
